### ISSUE TITLE
Solflare is spelled "Solfare" in the code

### ISSUE THREAD

**Issue by timothymcmackin** [rarimo/js-sdk#12]
The wallet's name is Solflare: https://solflare.com.

https://github.com/rarimo/js-sdk/blob/main/packages/provider/src/providers/solfare.ts#L24

**Comment by napalmpapalam** [comment]
Fixed in [https://github.com/rarimo/js-sdk/pull/14](https://github.com/rarimo/js-sdk/pull/14)
